### ISSUE TITLE
Add Latency support for the requests

### ISSUE THREAD

**Issue by jabrena** [typicode/jsonplaceholder#100]
Hi, I would like to know if it is possible to add a request parameter to add a kind of latency in the request.

One example from another alternative:
https://www.mocky.io/
https://www.mocky.io/v2/5185415ba171ea3a00704eed?mocky-delay=2000ms

Juan Antonio

**Comment by redaxmedia** [comment]
I found a temporary solution for that using [slowwly](https://github.com/rob-murray/slowwly):

http://slowwly.robertomurray.co.uk/delay/2000/url/https://jsonplaceholder.typicode.com/posts

**Comment by hjgraca** [comment]
Hey, you just need to pass _delay=2000 in the querystring.
Example: https://my-json-server.typicode.com/<your-username>/<your-repo> ?_delay=2000

**Comment by jabrena** [comment]
Thanks
