### ISSUE TITLE
Can't show specific resource with My JSON server

### ISSUE THREAD

**Issue by pateskinasy** [typicode/jsonplaceholder#101]
Hi!

Trying to get a specific response - i.e. first post (for my own JSON uploaded to My JSON server) like you get for your demo data
`https://my-json-server.typicode.com/typicode/demo/posts/1`

But (on my data), it only returns `{ }`

I can only get a response (on my data) for the analogous to `https://my-json-server.typicode.com/typicode/demo/posts` i.e. all posts

What am I missing?

**Comment by typicode** [comment]
Hi,

Can you retry? It's working for me right now.

```js
// https://my-json-server.typicode.com/typicode/demo/posts/1
{
  "id": 1,
  "title": "Post 1"
}
```

Requests are cached for 1 minute, so if you just changed your db.json, it may take a minute for changes to be reflected.

If you have a specific URL you can share with your data, I can have a look.

**Comment by pateskinasy** [comment]
Thanks for reverting quickly!

Yep, works on your data, but not on mine:
https://my-json-server.typicode.com/morsewall/random-quotes-vanillajs-rest-api/quotes/1

Any pointers?

**Comment by typicode** [comment]
Thanks for your patience and really sorry for the delay. I see what's the issue, quotes would need an `id` field. Something like:

```json
[
  {
    "id": 1,
    "quoteText": "\"Many of you appear concerned that we are wasting valuable lesson time, but I assure you we will go back to school the moment you start listening to science and give us a future.\"",
    "quoteAuthor": "@GretaThunberg"
  },
  {
    "id": 2,
    "quoteText": "\"I was fortunate to be born in a time and place where everyone told us to dream big. I could become whatever I wanted to. I could live wherever I wanted to. People like me had everything we needed and more. Things our grandparents could not even dream of. We had everything we could ever wish for and yet now we may have nothing. Now we probably don’t even have a future any more.\"",
    "quoteAuthor": "@GretaThunberg"
  },
```

Then https://my-json-server.typicode.com/morsewall/jsondb/quotes/1 will be able to pick the one with `"id": 1`

**Comment by pateskinasy** [comment]
Got it. Thanks for looking into it @typicode . Appreciated.
