### ISSUE TITLE
GET /users/2/todos return "userId": 1,

### ISSUE THREAD

**Issue by GrigK** [typicode/jsonplaceholder#117]
https://jsonplaceholder.typicode.com/users/2/todos
return:
[{
   "userId": 1,  <--- ???
   "id": 1,
   "title": "delectus aut autem",
   "completed": false
},
{ ...

**Comment by Yosefc** [comment]
Hi,

From what I can tell, if you want to get post from a certain user, you need to query that info.  There is a example in the documentation over [here](https://jsonplaceholder.typicode.com/guide.html#filteringresources).  (e.g. https://jsonplaceholder.typicode.com/posts?userId=2)

**Comment by typicode** [comment]
Thanks for the report :+1: It's (finally) fixed.
