### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by Gentlee** [typicode/jsonplaceholder#120]
Server doesn't respond.

**Comment by typicode** [comment]
Hi @Gentlee,

Thanks for the report! I've tried and it seems to be working. Could you give it another try?

**Comment by Gentlee** [comment]
@typicode yeah, sorry, opened from vpn, seems some problem with my provider.

**Comment by umbrella-kirill-karpov** [comment]
Hello, the same for me.

I'm from Russia. I've tried different Internet providers, but the server is not reachable.

```
nslookup jsonplaceholder.typicode.com

Non-authoritative answer:
Name:	jsonplaceholder.typicode.com
Address: 172.64.128.28
Name:	jsonplaceholder.typicode.com
Address: 172.64.129.28
``` 

```
whois 172.64.128.28 | grep cloud

Comment:        All Cloudflare abuse reporting can be done via https://www.cloudflare.com/abuse
OrgTechEmail:  rir@cloudflare.com
OrgNOCEmail:  noc@cloudflare.com
OrgAbuseEmail:  abuse@cloudflare.com
RAbuseEmail:  abuse@cloudflare.com
RTechEmail:  rir@cloudflare.com
RNOCEmail:  noc@cloudflare.com
```

I've managed to find `172.64.128.28` in Russia's IP blacklist: https://blocklist.rkn.gov.ru. Looks like your load balancer has giver you blocked IPs in our region.

Any chance to update configs?

**Comment by typicode** [comment]
Thanks for the details @Gentlee. I've contacted the support. Didn't find a way to update configs unfortunately.

**Comment by rockstar4095** [comment]
Now your resource is available from Russia, thank you very much!

**Comment by typicode** [comment]
Awesome! Thanks for letting me know 👍
