### ISSUE TITLE
sending same id(201) in response on post request

### ISSUE THREAD

**Issue by ItsBhatt** [typicode/jsonplaceholder#121]
i'm sending a post request using axios in react but getting same id in every element in response.

![image](https://user-images.githubusercontent.com/39770659/72344525-753d6000-36f7-11ea-801f-33f86942c615.png)

after post request getting same id 

- (201)

![image](https://user-images.githubusercontent.com/39770659/72344607-ab7adf80-36f7-11ea-9b8c-eb1dc6f3cff8.png)

- response -

![image](https://user-images.githubusercontent.com/39770659/72344775-14625780-36f8-11ea-91ea-e2c50b86fc11.png)

**Comment by 7KiLL** [comment]
Probably this is not an issue. Jsonplaceholder is simple REST mock, not working back-end with logic. It will not increment your ID, it simply add +1 to existing 200 items. It always will be 201.

**Comment by caslinecap** [comment]
thank you it was indeed that, it helped!
