### ISSUE TITLE
jsonplaceholder.typicode.com not working 

### ISSUE THREAD

**Issue by eikoshelev** [typicode/jsonplaceholder#122]
From iOS app:

```
NSLocalizedDescription=The request timed out.,  NSErrorFailingURLStringKey=https://jsonplaceholder.typicode.com/posts,  NSErrorFailingURLKey=https://jsonplaceholder.typicode.com/posts. 

Error sending request: The request timed out.
```

Also, when trying to open jsonplaceholder.typicode.com in a browser, the request also ends with a server timeout.

**Comment by eikoshelev** [comment]
well, it seems that this is a problem of access from a specific region, when trying to request from a different location (using vpn) everything works

**Comment by typicode** [comment]
Yes, it's currently blocked in Russia :/

**Comment by eikoshelev** [comment]
> Yes, it's currently blocked in Russia :/

Yes, unfortunately this is so :(

**Comment by susanwinters214** [comment]
When I go to: https://jsonplaceholder.typicode.com/
I get a Code 502 - I am in the USA
Is this website just down?
