### ISSUE TITLE
Heroku shit is giving error

### ISSUE THREAD

**Issue by kodmanyagha** [typicode/jsonplaceholder#126]
The link is here: https://jsonplaceholder.typicode.com/todos?_start=0&_limit=10

Waiting lots of time and then showing heroku error or Cloudflare 502 error.

![herokuerror](https://user-images.githubusercontent.com/3948692/75354038-61237b80-58bd-11ea-8f9f-defb33ce9495.png)

Why are you using heroku? Heroku is shit. Buy a server from contabo (10 euro vps is enough if you cache data) and then put your project to there. If you want I can become sponsor for server. Don't use heroku shit.

I'm learning vuejs from this video: https://www.youtube.com/watch?reload=9&v=Wy9q22isx3U
This video is using your service but heroku shit is blocking me now. I hate heroku shit!

**Comment by HenryMigo** [comment]
This is not constructive, I would either close this issue @kodmanyagha or change your wording. No need to be so aggressive.
