### ISSUE TITLE
timeout on posts

### ISSUE THREAD

**Issue by shimulxx** [typicode/jsonplaceholder#128]
Retrofit json timeout, response code 503 on onhttp..please fix this issueeeee

**Comment by rorynscott** [comment]
Having this issue as well. Anything we can do to help?

**Comment by pmusolino** [comment]
It seems that every request to `/posts/xxx` which was never server, goes in timeout the first time, but it works properly the second time.

**Comment by typicode** [comment]
Thanks for the issue. It should be good now :)
