### ISSUE TITLE
CORS Error when trying to make a PUT or PATCH request

### ISSUE THREAD

**Issue by ChristianPari** [typicode/jsonplaceholder#132]
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://jsonplaceholder.typicode.com/posts/1. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)." 
Getting this error each time i try to run any request

**Comment by namfal** [comment]
I got the same error earlier today, but not yesterday. Seems to be fine now though

**Comment by ChristianPari** [comment]
For real? Nah me and my friends are still having the issue, website won't even load up either
