### ISSUE TITLE
Getting 502 errors / long response times / Heroku error page

### ISSUE THREAD

**Issue by ganlub** [typicode/jsonplaceholder#133]
I am getting 502 issues accessing the landing page and really long times on the API and most of the times the Heroku error page.

I've waited a few days before opening an issue as I saw there were others resolved issues with similar contexts but this keeps happening.

Can I provide any additional information to help narrow this down?

**Comment by kodiii** [comment]
i also have this problem

**Comment by mushfiq814** [comment]
Can confirm loading issues today as well.

**Comment by iamtekson** [comment]
I have also same problem

**Comment by typicode** [comment]
Thanks for letting me know. Not getting 502 errors but some routes are slow. I'm having a look :+1:

**Comment by typicode** [comment]
Should be good now :)
