### ISSUE TITLE
Example for fetching '(...)/todos/1' on main website not working.

### ISSUE THREAD

**Issue by PiotrNap** [typicode/jsonplaceholder#147]
The example shown on placeholder isn't working, it gives :
`Uncaught SyntaxError: Invalid regular expression: missing /` in the browser console.

**Comment by parmeet9891** [comment]
@PiotrNap I have tried opening this website (directly as well as hitting as API in JS), both are working for me.

[https://codesandbox.io/s/busy-jones-713bj](url)

![Screenshot from 2020-11-01 18-48-02](https://user-images.githubusercontent.com/16643650/97804075-93b71c80-1c73-11eb-9684-27aff1958862.png)

Let me know if I interpret the wrong way!.

**Comment by PiotrNap** [comment]
Yes, it is working now. Could be an an issue due to changing the website design?
