### ISSUE TITLE
Documentation on POST /posts is incorrect

### ISSUE THREAD

**Issue by mattiasnordqvist** [typicode/jsonplaceholder#16]
https://github.com/typicode/jsonplaceholder#creating-a-resource states that an object with all values set is returned. However, only a newly generated id is returned.

**Comment by typicode** [comment]
Hi Mattias,

Thanks :+1: , I've updated the documentation.
It now shows what's really returned by the site.

**Comment by mattiasnordqvist** [comment]
Great but maybe I was unclear. :)

The documentation now says that this is returned.
```json
{
  id: 101,
  title: 'foo',
  body: 'bar',
  userId: 1
}
```
However, this is what is returned:
```json
{
  id: 101
}
```

**Comment by typicode** [comment]
Oh, I see. Actually I don't know how to reproduce.
How do you make the request?

![screenshot](https://cloud.githubusercontent.com/assets/5502029/7223812/bca383bc-e728-11e4-9bc9-bb77ab339745.png)

**Comment by mattiasnordqvist** [comment]
I'm using Postman, a google chrome extension.

![image](https://cloud.githubusercontent.com/assets/5485546/7224954/29663174-e739-11e4-8fb8-d08087a3f397.png)

**Comment by typicode** [comment]
Ok did a test, it seems like you need to set a Header so it sends it as `application/json` and not as `application/text`.

![screenshot](https://cloud.githubusercontent.com/assets/5502029/7244487/9849ade8-e7dc-11e4-95b4-b532f6e27f3f.png)

**Comment by mattiasnordqvist** [comment]
Dude, your right! Sorry, my bad. :( Well, at least the random number was replaced with 101. :) I'm closing this issue.

**Comment by typicode** [comment]
No worries, good that it work now :)
