### ISSUE TITLE
Jsonplaceholder website is down

### ISSUE THREAD

**Issue by quiquesk8** [typicode/jsonplaceholder#163]
Hi, when i try to navigate into [https://jsonplaceholder.typicode.com/](url) results in a Heroku page with the following message "There's nothing here, yet." on the page.
Thanks, Quique.

**Comment by snooze92** [comment]
Duplicate of https://github.com/typicode/jsonplaceholder/issues/161

**Comment by RitikDua** [comment]
It is working right now
