### ISSUE TITLE
Getting 503 errors and Heroku error page

### ISSUE THREAD

**Issue by brunaschneiders** [typicode/jsonplaceholder#174]
Hello all!!

I'm getting an error saying:

<img width="423" alt="2021-08-23 (2)" src="https://user-images.githubusercontent.com/64864277/130522492-6c09e36a-781a-41c1-8536-4387b61f465a.png">

the same occurs with these:

- https://jsonplaceholder.typicode.com/albums?userId=5
- https://jsonplaceholder.typicode.com/photos?albumId=10

Besides, if I access this url, https://jsonplaceholder.typicode.com/photos?albumId=10, I'm having this error:

<img width="877" alt="2021-08-23 (4)" src="https://user-images.githubusercontent.com/64864277/130523121-0343303c-fc41-494f-925b-0572e09a1761.png">

Could someone help me with it?

Thank you!!

**Comment by typicode** [comment]
Fixed, thank you for the heads up :+1:
