### ISSUE TITLE
POST posts now returns 404

### ISSUE THREAD

**Issue by DalSoft** [typicode/jsonplaceholder#20]
Your example http://jsonplaceholder.typicode.com/

POST http://jsonplaceholder.typicode.com/posts

Now returns a 404. It was working fine before.

**Comment by typicode** [comment]
@DalSoft thanks for letting me know :)
But I don't know how to reproduce? It seems to work when I test it.

![screenshot from 2015-08-03 19 06 21](https://cloud.githubusercontent.com/assets/5502029/9043023/d996b218-3a12-11e5-9cd7-9eada1e2c319.png)

**Comment by dexterallengalvez** [comment]
This is also happening to me. Were you able to resolve this?

**Comment by DalSoft** [comment]
My issue was the resources were case sensitive

**Comment by DalSoft** [comment]
No works perfectly regardless of case for example https://jsonplaceholder.typicode.com/PoSts
