### ISSUE TITLE
Is there a request rate limit?

### ISSUE THREAD

**Issue by mossinipaolo** [typicode/jsonplaceholder#207]
I am using jsonplaceholder as part of my development and testing workflow, and I was wondering if there are any request rate limits that I should be aware of? 
I want to ensure that my usage remains within acceptable bounds, especially for larger-scale automated testing.

Could you provide some clarification on whether there are rate limits in place, and if so, what those limits are?

Thanks in advance for your time and help!

**Comment by typicode** [comment]
No rate limit but please don't abuse it, it's a free project :)
