### ISSUE TITLE
/photos endpoint returns 5000 results

### ISSUE THREAD

**Issue by gpbmike** [typicode/jsonplaceholder#22]
I'm not sure if this is intentional but it took me by surprise. Under **Resources** on http://jsonplaceholder.typicode.com/ there is a mention of the `/photos` endpoint containing 200 items, but when I hit said endpoint it returns 5000.

```javascript
$.ajax('http://jsonplaceholder.typicode.com/photos/', {
  method: 'GET'
}).then(function(data) {
  console.log(data.length);
});
// 5000
```

My laptop fans kicked into overdrive. :smile:

**Comment by typicode** [comment]
Not intentional :)
Thanks for letting me know, it should be good now.
