### ISSUE TITLE
DELETE resource returns status 200

### ISSUE THREAD

**Issue by pkokoshnikov** [typicode/jsonplaceholder#25]
I read your how-to(https://github.com/typicode/jsonplaceholder#how-to) and found mistake. When i try to DELETE a resource
$.ajax('http://jsonplaceholder.typicode.com/posts/1', {
  method: 'DELETE'
});
. 
Service returns status code 200. But in your how-to is written that it must be 204.(// DELETE returns a 204 status only)

**Comment by typicode** [comment]
Thank you, it has been updated.
