### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by antoniputra** [typicode/jsonplaceholder#27]
is there a configuration to doing pagination?

something like:
http://jsonplaceholder.typicode.com/posts?page=2&limit=10&sort=latest

**Comment by typicode** [comment]
Hi @antoniputra,

You can use `_start` and `_limit`:
http://jsonplaceholder.typicode.com/posts?_start=10&_limit=10

There's also a custom header `X-Total-Count` in the response.

**Comment by antoniputra** [comment]
Awesome. :+1:

**Comment by firxworx** [comment]
I came across this when searching if/how the JSONPlaceholder API supported paging. 

I implemented a codesandbox example that uses the `_page` and `_limit` parameters to implement paging:

https://codesandbox.io/s/api-pagination-with-react-router-hooks-i0912

In general, the API supports everything implemented by JSON Server. You can check that project's README/docs for paging/sort/filter/search related parameters: https://github.com/typicode/json-server
