### ISSUE TITLE
jsonplaceholder command not found in Git bash

### ISSUE THREAD

**Issue by Brian1111** [typicode/jsonplaceholder#28]
I installed jsonplaceholder version 0.3.1 using the following command "npm install jsonplaceholder -g"; however, when at the command prompt in Git bash I type "jsonplaceholder", I receive the following message:  

"bash: jsonplaceholder: command not found"

**Comment by typicode** [comment]
Hi @Brian1111,

Thank you for reporting :) seems like the command has been removed after a refactoring.

As a workaround, If you want to use JSONPlaceholder locally, please install `json-server` and load JSONPlaceholder data:

```js
npm install -g json-server
json-server http://jsonplaceholder.typicode.com/db
```

**Comment by Brian1111** [comment]
Hi @typicode,

Thank you for the information.  jsonplaceholder is installed in the following directory:  "C:\Railsinstaller\Git\usr\local>"  I could run it on Windows PowerShell Terminal by typing the following command:  ".\jsonplaceholder"

However, I cannot run it on Git Bash Terminal.  I reinstalled json-server, and typed the following as you stated: "json-server http://jsonplaceholder.typicode.com/db".  Still I am getting the same error message: "bash: json-server: command not found"

**Comment by typicode** [comment]
That's kind of weird, I'm not using PowerShell so I don't know it very well, but it may be related to your Node installation/PATH environment variable. Did you manage to install other CLIs globally using Node?

**Comment by Brian1111** [comment]
I fixed the problem. I went to the directory "C:\Users\Username" and opened the file ".npmrc"

Then I changed the prefix from "prefix=C:/RailsInstaller/Git/usr/local" to: "prefix=C:\Users\Username\AppData\Roaming\npm"

**Comment by FlappyHeart** [comment]
Same issues for me, and I want to use the server remotely.
