### ISSUE TITLE
Implement pagination

### ISSUE THREAD

**Issue by Robinfr** [typicode/jsonplaceholder#29]
It would be awesome if we could have some pagination in the API. E.g. `limit` and `start`.

**Comment by Robinfr** [comment]
Never mind, apparently it already [exists](https://github.com/typicode/jsonplaceholder/issues/27). It's not documented on the GitHub page however, maybe it can be added there?

**Comment by Robinfr** [comment]
I'm also missing a way to get the total amount of objects (without retrieving all of the objects), so it's still impossible to implement pagination.

**Comment by typicode** [comment]
Hi @Robinfr,

Thank you for the feedback. You can find all the documentation and available parameters in [JSON Server](https://github.com/typicode/json-server) README.

There's `X_TOTAL_COUNT` header that is added when you use `_start` and `_limit`:
https://github.com/typicode/json-server#slice

But for JSONPlaceholder, I prefer to document only what I'm pretty sure won't change in JSON Server. In other words, consider that what isn't documented may change.

If you need to make sure it'll always work, add JSON Server as a dependency to your project.

**Comment by Robinfr** [comment]
Thanks for replying. I will do that instead to make sure it will work in the future.
