### ISSUE TITLE
Users data corrupted

### ISSUE THREAD

**Issue by rmat0n** [typicode/jsonplaceholder#30]
Hi, seems that `/users` is corrupted as it returns 20 users (instead of 10). Note that some of them have no data inside, see curl output in [this file](https://github.com/typicode/jsonplaceholder/files/261440/users.txt).
Thanks

**Comment by Jotunblood** [comment]
Most all of the data is corrupted, and `/posts` is a jumbled mess. I also sent an email in hopes that this gets resolved quickly.

**Comment by capslockpirate** [comment]
Just did a test, looks like whatever prevented actually creating and deleting records changed somehow, I was able to actually create a new user that was persisted:
`{
name: "test",
email: "test@testing.test",
website: "google.com",
id: 18
}`

**Comment by typicode** [comment]
Thank you for the heads up. I'll have a look right now.

**Comment by typicode** [comment]
There was a breaking change in [lowdb](http://github.com/typicode/lowdb) API and I didn't update JSONPlaceholder accordingly. I've deployed the fix so it should be good now.

Tests have been updated too.
I'm testing now that concurrent requests don't modify data to be sure it won't happen again.

Sorry for any inconvenience, and thanks a lot again all for letting me know :) :+1:

**Comment by rmat0n** [comment]
@typicode well done! great service btw 😉

**Comment by typicode** [comment]
@rmat0n thanks :)
