### ISSUE TITLE
http://jsonplaceholder.typicode.com/ is down

### ISSUE THREAD

**Issue by mattdelacey** [typicode/jsonplaceholder#33]

**Comment by mattdelacey** [comment]
Looks like it is back up again.

**Comment by rmat0n** [comment]
Down again, right now.

**Comment by typicode** [comment]
Thank you @rmat0n, seems to work again (at least for me). I'm monitoring it right now.
Will work on it today and I've tried a few things this week to improve things after @mattdelacey report.

**Comment by rmat0n** [comment]
@typicode great news thx, up and down regularly (up for some hours now)

**Comment by typicode** [comment]
Closing, the site seems stable for the past few weeks.

**Comment by Grami-mhd** [comment]
it's down again ...
