### ISSUE TITLE
/photos thumbnail has different color

### ISSUE THREAD

**Issue by Hipska** [typicode/jsonplaceholder#38]
The original image and the thumbnail of it always have a different color, which is confusing and makes one think the example code has some problems.

**Comment by typicode** [comment]
That's a good point 👍 I'll see what can be done.

**Comment by shortstuffsushi** [comment]
I've greatly enjoyed this service so far, but also felt like it could benefit from having the same color for the thumbnail and full size images. I updated the data file accordingly, let me know if that's adequate. It seems like that's all there is to it.

**Comment by typicode** [comment]
@shortstuffsushi Thank you :+1:  :) merging it
