### ISSUE TITLE
Getting heroku application error on https://jsonplaceholder.typicode.com/comments/1

### ISSUE THREAD

**Issue by brian-mann** [typicode/jsonplaceholder#39]
![screen shot 2016-10-12 at 11 16 04 pm](https://cloud.githubusercontent.com/assets/1268976/19335503/df59ddf8-90d1-11e6-9b11-9de6189a5729.png)

**Comment by typicode** [comment]
Hi @brian-mann,

Thank you for the heads-up. I've not done any deployment so it was maybe just some temporary issue.

Can you retry? It seems to work now.

And if it happens again do not hesitate to let me know :)

**Comment by typicode** [comment]
My bad, I made a mistake with heroku config and it probably worked on my side because of the cache.
It should be good now.

**Comment by brian-mann** [comment]
Much appreciated.

We use your site for the Cypress.io kitchen sink to demonstrate `cy.request` handling.

https://github.com/cypress-io/cypress-example-kitchensink

**Comment by typicode** [comment]
You're welcome.
btw, cypress.io looks promising :)
