### ISSUE TITLE
what's wrong with this ? what should I do ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [typicode/jsonplaceholder#41]
# <del>Run this code in a console or from anywhere (CORS and JSONP supported).</del>
![smg](https://cloud.githubusercontent.com/assets/18028768/19953997/cbb27218-a1ae-11e6-9bbe-22348a764cd4.PNG)

```js
var root = 'http://jsonplaceholder.typicode.com';
$.ajax({
    url: root + '/posts/1',
    method: 'GET'
}).then(function(data) {
    console.log(data);
});

``` 

![jquery-ajax -error](https://cloud.githubusercontent.com/assets/18028768/19954019/0075d832-a1af-11e6-9fd8-36389bbd64bc.PNG)

**Comment by typicode** [comment]
Hi @xgqfrms-GitHub,

Sorry for the confusion, it should be run in the browser console when you are on http://jsonplaceholder.typicode.com/ or any page that has jQuery loaded.

![screenshot](https://cloud.githubusercontent.com/assets/5502029/19964331/775aa9d4-a1c1-11e6-85d3-ee94b80434e7.png)

If you want to make a request with Node, you can use [request](https://github.com/request/request) or [got](https://github.com/sindresorhus/got).

Hope this helps :)

**Comment by xgqfrms-GitHub** [comment]
Anyway, thanks for you reply!

**Comment by typicode** [comment]
there's a great tutorial on egghead.io if you need more:
https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server
