### ISSUE TITLE
GitTip

### ISSUE THREAD

**Issue by baweaver** [typicode/jsonplaceholder#43]
You might consider getting a tip option up some time, I'd chip in a few bucks to much of anything that saves me time.

**Comment by typicode** [comment]
Hi @baweaver 

Thank you for the idea :)

Took me some time, but I've finally created a patreon page https://www.patreon.com/typicode.

It's pretty empty for the moment, but if you want to support jsonplaceholder or my other projects, you can do it there.

Thanks again.
