### ISSUE TITLE
How get X elements?

### ISSUE THREAD

**Issue by diemax** [typicode/jsonplaceholder#48]
Hi @typicode ! Great project 
Just a little question, is there a parameter that I can send for example to the `comments` endpoint for getting `X` elements? for example `/comments?qty=30` ? 
Or maybe a range: `/comments?1,30`

Thanks!

**Comment by romualdr** [comment]
Hello @diemax !

Here is the answer from @typicode found in another issue

> You can use _start and _limit:
> http://jsonplaceholder.typicode.com/posts?_start=10&_limit=10
>
> There's also a custom header X-Total-Count in the response.

**Comment by typicode** [comment]
Hi @diemax, sorry was lacking time to reply.
Thank you for the help @diemax!

You can also use:
http://jsonplaceholder.typicode.com/posts?_page=1&_limit=5
