### ISSUE TITLE
POST to '/posts' returns all (100) posts instead of the newly POSTed post

### ISSUE THREAD

**Issue by Mertsch** [typicode/jsonplaceholder#52]
## Desired
```
// POST adds a random id to the object sent
$.ajax('http://jsonplaceholder.typicode.com/posts', {
  method: 'POST',
  data: {
    title: 'foo',
    body: 'bar',
    userId: 1
  }
}).then(function(data) {
  console.log(data);
});

/* will return
{
  id: 101,
  title: 'foo',
  body: 'bar',
  userId: 1
}
*/
```
## Actual
Returns 100 posts

Last time it worked November 5, 2017 03:00 UTC

**Comment by Mertsch** [comment]
May be related to https://github.com/typicode/json-server/issues/678

**Comment by typicode** [comment]
Hi @Mertsch,

I've tried it now, but can't seem to reproduce. Could you give it another try?

![screenshot from 2017-11-06 13 21 15](https://user-images.githubusercontent.com/5502029/32440896-7a436e0a-c2f5-11e7-83cc-a1606591b523.png)

**Comment by Mertsch** [comment]
@typicode Hmmm that is strange, my UnitTest (C# with `HttpClient`) is still failing (getting an array as result).
I have moved away from using `http://jsonplaceholder.typicode.com/posts` and am now creating my own test-HTTP server which solves the issue for me and continues to prove it's not an issue with my code (code did not change in a few weeks and tests run daily)

**Comment by ManasiRoy** [comment]
I used the JSON placeholder post. After submitting the post it is showing in console.log but can not show in the Blog post. Any suggestion. Please help.
This is my code-

    state = {
        title: '',
        body: '',
        post: []
    }
    onChange = (e) => {
        this.setState({
            [e.target.name]: e.target.value
        })
    }
    onSubmit = (e) => {
        e.preventDefault();

        const post = {
            title: this.state.title,
            body: this.state.body
        }

        fetch('https://jsonplaceholder.typicode.com/posts', {
            method: "POST",
            headers: {
                'content-type': 'application/json'
            },
            body: JSON.stringify(post)
        })
            .then(response => response.json())
            .then(json => { console.log(json); return json; })

            //.then(json => console.log(json))
            .then(json => this.setState({
                post: json
            }))
    }

**Comment by Mertsch** [comment]
Seems fixed
