### ISSUE TITLE
Replace jQuery with fetch in examples

### ISSUE THREAD

**Issue by typicode** [typicode/jsonplaceholder#53]
# Todo

Currently, examples use jQuery. Since modern browsers now support fetch, it would be great to have updated examples :)

* Update examples in README
* Update index.html
* Add fetch polyfill from [unpkg](https://unpkg.com/) in index.html

**Comment by vivek12345** [comment]
@typicode can I take this up?

**Comment by typicode** [comment]
Sure!

**Comment by vivek12345** [comment]
@typicode All your post end points are giving me a 301, leading to get calls.
```
$.ajax('http://jsonplaceholder.typicode.com/posts', {
  method: 'POST',
  data: {
    title: 'foo',
    body: 'bar',
    userId: 1
  }
}).then(function(data) {
  console.log(data);
});
```
This code itself is giving that issue.

**Comment by typicode** [comment]
I've added a redirection from http to https.
So GET request should be made to https://jsonplaceholder.typicode.com/posts

**Comment by vivek12345** [comment]
@typicode So should I replace all my POST and get url's with https ones.

**Comment by vivek12345** [comment]
@typicode I have updated the url's and have sent a PR for the same as well.
[PR#54](https://github.com/typicode/jsonplaceholder/pull/54)

**Comment by typicode** [comment]
Merged, thanks again
