### ISSUE TITLE
How to fetch metadata such as number of entries?

### ISSUE THREAD

**Issue by simkimsia** [typicode/jsonplaceholder#63]
Hi there, 

I have been using this to test reactjs apps. Is there a way to fetch metadata such as number of entries?

**Comment by alex2118** [comment]
haven't tried this API out yet but I am currently working on a similar task, have you tried Object.keys(object).length?

**Comment by simkimsia** [comment]
it's okay @alex2118 I have decided to build my own API. Thanks 👍
