### ISSUE TITLE
[Bug] /posts returns string for userId instead of number

### ISSUE THREAD

**Issue by AnyhowStep** [typicode/jsonplaceholder#74]
https://jsonplaceholder.typicode.com/posts

```
/*snip*/
  {
    "userId": 10,
    "id": 100,
    "title": "at nam consequatur ea labore ea harum",
    "body": "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut"
  },
  {
    "title": "foo",
    "body": "bar",
    "userId": "4", //Should be `4`, not `"4"`
    "id": 101
  }
]
```

**Comment by mikeerickson** [comment]
@AnyhowStep How is this affecting your testing?  There are a number of ways to get around this, without them having to make changes.  If you have a case where this is causing a problem, post a snippet of code and I can show you how to get around it.

**Comment by typicode** [comment]
Hi,

Thanks for the issue. There shouldn't be a 101st item when doing a GET on https://jsonplaceholder.typicode.com/posts. If there is, it's a bug in JSONPlaceholder.

I've checked and I get 100:

```
...
    "userId": 10,
    "id": 99,
    "title": "temporibus sit alias delectus eligendi possimus magni",
    "body": "quo deleniti praesentium dicta non quod\naut est molestias\nmolestias et officia quis nihil\nitaque dolorem quia"
  },
  {
    "userId": 10,
    "id": 100,
    "title": "at nam consequatur ea labore ea harum",
    "body": "cupiditate quo est a modi nesciunt soluta\nipsa voluptas error itaque dicta in\nautem qui minus magnam et distinctio eum\naccusamus ratione error aut"
  }
]
```

Are you still getting 101 items? Is it random?

**Comment by mikeerickson** [comment]
@typicode Hitting the above entrypoint you supplied, the last row in the result is indeed a 101

![image](https://user-images.githubusercontent.com/183153/44126311-594fef00-9fec-11e8-8fbd-21bdbe0e4bc0.png)

**Comment by typicode** [comment]
if it returns `101` again, please let me know :) (seeing also 100 items at the moment)
