### ISSUE TITLE
There's now an extra invalid post in the /posts endpoint

### ISSUE THREAD

**Issue by tfcporciuncula** [typicode/jsonplaceholder#77]
https://jsonplaceholder.typicode.com/posts

There are 100 posts as always but if you scroll down to the end, there's an extra one which has only an id:

```
{
  "id": 101
}
```

That's not intended, or is it?

**Comment by tfcporciuncula** [comment]
I'm closing this since it seems it's been fixed. If it ever happens again I'll try to open a new one with the goal of finding the root cause.

**Comment by typicode** [comment]
Thanks for the report, and you're right it's not intended.

I've created a test for this case:
https://github.com/typicode/jsonplaceholder/blob/master/test/app.js#L22

But maybe it's not 100% reliable :/
