### ISSUE TITLE
Unable to receive the proper return

### ISSUE THREAD

**Issue by Danich89** [typicode/jsonplaceholder#86]
I'm trying to run the fetch command that is given as an example, i.e:
fetch('https://jsonplaceholder.typicode.com/posts', {
    method: 'POST',
    body: JSON.stringify({
      title: 'foo',
      body: 'bar',
      userId: 1
    }),
    headers: {
      "Content-type": "application/json; charset=UTF-8"
    }
  })
  .then(response => response.json())
  .then(json => console.log(json))

However, instead of the mentioned return, all I receive is:
{
    "id": 101
}

Is there a problem with the API?

**Comment by typicode** [comment]
Tried the example in the README again, seems to work.
Might have been a temporary issue?

Thanks for the report.
