### ISSUE TITLE
`/users/1/todos` returns todos for all users

### ISSUE THREAD

**Issue by Asday** [typicode/jsonplaceholder#96]
https://jsonplaceholder.typicode.com/users/1/todos

**Comment by typicode** [comment]
Thanks for letting me know

**Comment by typicode** [comment]
Seems to be related to https://github.com/typicode/jsonplaceholder/issues/91

**Comment by typicode** [comment]
Closing as it's a duplicate

**Comment by Asday** [comment]
Right you are, sorry about that.  :heart:
