### ISSUE TITLE
Compress JSON response

### ISSUE THREAD

**Issue by quanganhtran** [typicode/jsonplaceholder#97]
Hi, thank you for the great work. This tool has helped me a lot.

Is it at the moment possible to receive compressed JSON as a response? If not, what is the way you'd recommend to achieve this if I would run my own local jsonplaceholder?

(keywords for search: compress compressed minify minified zipped)

**Comment by typicode** [comment]
Hi @quanganhtran,

What do you mean compressed JSON? Responses should already be gzipped.

**Comment by quanganhtran** [comment]
Hi, sorry for the wrong terminology. What I meant is minified JSON. But now I think about it, this doesn't give nearly as much size reduction as gzipping (which is already done)

**Comment by typicode** [comment]
No worries :+1:
